### ISSUE TITLE
Why this code is not working

### ISSUE THREAD

**Issue by suman2mandal** [suman2mandal/First-Machine-learning#1]
This is my first project on machine learning and it is not working please help me
[Irish.txt](https://github.com/suman2mandal/First-Machine-learning/files/2565793/Irish.txt)

**Comment by daniela-llivina** [comment]
I see you are not working with the features Petal_Length and Petal_Width. Is that right?

**Comment by suman2mandal** [comment]
Thank you for your response.Now it is working fine and please tell me how
it "reshape(1, -1))" is working.

**Comment by daniela-llivina** [comment]
Hi @suman2mandal,

When you don't use the "reshape(1, -1)" you get an error message like this one: 

![screenshot from 2018-11-12 08-27-12](https://user-images.githubusercontent.com/35237645/48350379-f82adc80-e654-11e8-9276-52369ccf56a2.png)

As you can see, they give you the solution on the message. You can also check the numpy.reshape() documentation here https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.reshape.html

Hope this helps!

**Comment by suman2mandal** [comment]
Thank you and kindly tell me what IDE you are using because in my default
IDLE it is not showing that much information

**Comment by daniela-llivina** [comment]
I'm not using any IDE, just Visual Studio Code on Linux and running the .py in the terminal

**Comment by suman2mandal** [comment]
and how i add Petal_Length and Petal_Width in 2D graph?

**Comment by daniela-llivina** [comment]
You cannot do that. If you add Petal_Length and Petal_Width then you'll be working with 4 features, hence 4 dimensions. So, if you use Petal_Length and Petal_Width you can predict but no show in a graph.

**Comment by daniela-llivina** [comment]
Yes, should predict with the same amount of feature you used to train your model. In this case you have a dataset with 4 features, right? So, you train your model with all features and then predict with 4 features.

**Comment by suman2mandal** [comment]
Miss Llivina may i ask how and from where you learn machine learning
because I am just starting to learn from coursera

**Comment by daniela-llivina** [comment]
I studied machine learning at school and then for my thesis. To start I strongly recommend you Andrew Ng's course on coursera. I learned a lot from this course when I was starting. Hope this help.

**Comment by suman2mandal** [comment]
yes i take Mr. Ng's course first
